### ISSUE TITLE
no custom builtin elements in WebKit

### ISSUE THREAD

**Issue by lingtalfi** [Polymer/project#30]
On this thread: https://github.com/w3c/webcomponents/issues/544, user rniwa says:

`Like we've stated multiple times in the past, we're not going to implement custom builtin elements in WebKit but all other aspects of custom elements should be interoperable across browsers.`

What's your reaction about it?

**Comment by tjsavage** [comment]
We're generally very supportive of custom builtin elements for many different reasons, and we'll work with standards bodies to land on a good solution.

It's unfortunately not easy to just shim support for this on top of native custom elements - you basically need to use the full custom elements polyfill in order to use these. We really don't want to force all Polymer users to use the full custom elements polyfill on Safari when it does ship custom elements natively. For this reason, Polymer currently doesn't support building type-extension elements in the [2.0-preview](https://github.com/polymer/polymer/tree/2.0-preview), and we won't encourage its use right now to avoid indefinite reliance on the Custom Elements polyfill. Instead, a wrapper custom element can surround a native element, like `<a is="my-anchor">...</a>` becomes `<my-anchor><a>...</a></my-anchor>`. For all of the elements that ship with Polymer - like `dom-repeat`, `dom-bind`, etc. - we will use this approach.

**Comment by lingtalfi** [comment]
Thanks

**Comment by prushforth** [comment]
I've written a type-extension custom element in Polymer ^1.5.  It would be ideal to be able to continue this line of development in 2.x, but will you maintain 1.x until a platform standard for custom built-ins is agreed on?

**Comment by tjsavage** [comment]
@prushforth It's likely that at some point relatively early-on, 2.x will support building type extension elements if you're willing to bring in the whole CE polyfill. We'll be continuing to do critical bug fixes on 1.x for some time. So you should certainly have a safe path forward.

**Comment by prushforth** [comment]
Excellent news, thank you. Sounds like pollyfilling will be necessary long-term, but I'm ok with that.
