### ISSUE TITLE
Customized built-in / type extension elements

### ISSUE THREAD

**Issue by prushforth** [Polymer/project#32]
Hi,

Thank you for your good work on Custom Elements so far, Polymer team.  Keep it up!  You guys are changing everything.

However, I just came across [this page](https://www.polymer-project.org/2.0/docs/about_20#type-extension) and I am disappointed.  Does it really matter that a polyfill is necessary on Safari?  This is why Custom Elements matter, I think.  They give the platform a way to experiment with new semantics, in a way that does not harm anybody's business.  Please keep customised built-in elements, even with a polyfill.  Apple [used to](http://www.apple.com/hotnews/thoughts-on-flash/) support Web standards, maybe they will come around. 

BTW, this matters to me because I have spent quite a bit of time and effort designing a customized built-in `<map>` element, which was built with the intentions of the Extensible Web in mind.   There is a demo and blog post about this [here](http://maps4html.github.io/Web-Map-Custom-Element/blog/progressive-web-maps.html).  Just like with the Web components shim, and indeed Polymer itself, the plan (was) that the need for the customised type extension element would over time disappear.  With the help of the Custom Elements customised built-in element spec this was possible, but without it, the transition to 'native' will be much more painful, I think.  (Gonna happen either way tho :-)! 

I have mentioned this in other people's now-closed issue, but I wanted to be explicit about my needs, hence this issue, and certainly the hour is getting late with 2.0 seemingly coming out soon.

**Comment by prushforth** [comment]
Note that work on customised built-in is ongoing in [chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=652579]

**Comment by tjsavage** [comment]
Thanks for the kind words!

We totally agree - customized built-in elements are hugely valuable, and something we want to see broadly supported. There are three points that lead us to the strategy described [here](https://www.polymer-project.org/2.0/docs/about_20#type-extension) for 2.0:

- [Webkit's current position](https://github.com/w3c/webcomponents/issues/509#issuecomment-233419167) on is=
- Webkit's great [progress on Custom Elements v1 overall](https://bugs.webkit.org/show_bug.cgi?id=164242)
- The fact that to polyfill is=, you basically need to bring along an entire custom elements polyfill, even on browsers that natively support custom elements.

Our primary motive given this environment is to make it possible for developers to use Polymer on Safari without polyfills. This means Polymer 2.0 itself can't use custom built-in elements (like `<template is="dom-repeat">` and friends did in 1.0). And it also means for the broader ecosystem, we can't really encourage usage of type-extension elements, as using a single type-extension on a page means having to bring along the entire polyfill.

That said, we're still absolutely keen on continuing to work with Webkit and others to make type-extension possible in a cross-browser way. This is super high on the priority list after the 2.0 release. We want to make sure that direction we push forward with 2.x type-extension support is one that all browsers agree on, so that it's a true "polyfill."

**Comment by prushforth** [comment]
> we're still absolutely keen on continuing to work with Webkit and others to make type-extension possible in a cross-browser way

That's great.  Although it will be my first foray, I am starting a Chapters.io meetup in Ottawa this month, and one of the topics I hope to lead with is custom elements.  I haven't seen too much about CE on WICG, but I would hope to take our feedback there, even though it seems to have been a between-the-browsers discussion so far, I think it might help for browsers to hear some more public feedback about this, and not just from their peers.  

> make sure that ... 2.x type-extension support is one that all browsers agree on, so that it's a true "polyfill."
Seems to be a challenge so far, but sounds good. Please let me know if I / we can help in some way.  I think you'll find pretty good community support for  the feature.  Can you please leave this issue open for now.

Thanks

**Comment by tjsavage** [comment]
>  I am starting a Chapters.io meetup in Ottawa this month, and one of the topics I hope to lead with is custom elements... even though it seems to have been a between-the-browsers discussion so far, I think it might help for browsers to hear some more public feedback about this, and not just from their peers.

Absolutely. This is awesome. Exactly the kind of feedback & approach that can shift the space & inform the specs. Thank you!

> Please let me know if I / we can help in some way. I think you'll find pretty good community support for the feature. Can you please leave this issue open for now.

Definitely - will do! I agree, this does seem like a pressing issue for the community. The more this need can be made clear & the particular use-cases explained in different forums, the better. Will definitely leave this issue open until we are locked in to a standards-based cross-browser solution.
