### ISSUE TITLE
Why is router planned as a polymer element?

### ISSUE THREAD

**Issue by laco0416** [Polymer/project#4]
In the roadmap (https://github.com/Polymer/project/blob/master/Roadmap.md#application-rails), a `router` is planned as an element.
Routing (URL-State Mapping) is a job of Web Application Framework (like Angular). Polymer is a library to create custom elements easily. Aren't there any mismatches about responsibilities?

**Comment by ebidel** [comment]
Developers have been asking for a routing element from us for a long time. I think it's time to finally provide recommendations. Some folks also don't want to use a full framework just for routing capabilities.

**Comment by laco0416** [comment]
Yes, I can understand that needs. Routing is very important foundation for building web applications. 
Can I understand that this policy change says Polymer will be a framework?

**Comment by ebidel** [comment]
I don't think there are any policy changes. There's an element for that is the MO :) @tjsavage also spoke about the Carbon elements in his Polymer summit keynote (https://www.youtube.com/watch?v=jVn8tlnwAEs). 

A key difference is that a routing element is standalone and not part of Polymer core. That is, users can _chose_ to use that element if they'd like to. Otherwise, stick with their favorite and/or have a framework do it. We've had several incarnations of routing elements (3rd party and our own labs) for the past couple of years. I think it's time to have an official recommendation here.

**Comment by laco0416** [comment]
> I don't think there are any policy changes. 
Ok, thanks. I felt relieved! I want to use Polymer with Angular2 or React. :two_men_holding_hands:

**Comment by ebidel** [comment]
Yea, no changes there!

**Comment by floogulinc** [comment]
Many of the Polymer elements already do various functions of a web app framework. The point of custom elements is that you can pick and choose to build a web app with what you want. The elements made by the Polymer team are just one option among many and are not part of the core Polymer library.

**Comment by ebidel** [comment]
Well said. We like to think of it as "building blocks to make an entire app".

**Comment by ebidel** [comment]
Closing since we've mentioned this in our Summit and I/O.
